name: blurhash_web
description: The web implementation of blurhash
homepage: https://github.com/Raincal/blurhash/tree/master/blurhash_web
repository: https://github.com/Raincal/blurhash/tree/master/blurhash_web
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.24.0"

dependencies:
  blurhash_dart: ^1.2.1

  image: ^4.0.17
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BlurhashPlugin
        fileName: blurhash_web.dart
